baseURL = "https://timothyjv.com/"
languageCode = "en-us"
title = "Timothy Volk"

[params]
    about = """I'm a software developer who likes to draw, philosophize, and
    write the occasional blog post. Hope you find something interesting!"""
    email = "hi@timothyjv.com"
